apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscale-script
data:
  {{- $files := .Files }}
  {{- range tuple "server.py" "client.py"}}
  {{ . }}: |-
    {{- $files.Get . | nindent 4}}
  {{- end }}